//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAgencyOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Received_Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods_Received_Note()
        {
            this.ImportedItems = new HashSet<ImportedItem>();
        }
    
        public int Invoice_ID { get; set; }
        public int TotalQuantityItems { get; set; }
        public double Total_Imported_Price { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Manager_ID { get; set; }
    
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportedItem> ImportedItems { get; set; }
    }
}
