//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAgencyOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportedItem
    {
        public int TotalItemsQuantity { get; set; }
        public double TotalItemsPrice { get; set; }
        public int Invoice_ID { get; set; }
        public string ItemsID { get; set; }
    
        public virtual Goods_Received_Note Goods_Received_Note { get; set; }
        public virtual Item Item { get; set; }
    }
}
